### ISSUE TITLE
B523 D2 and D3 pins different compared to the data sheet

### ISSUE THREAD

**Issue by thrmttnw** [particle-iot/docs-tutorials#1]
Using the B523 eagle part from this project, and comparing it with the B523 data sheet, I found:

Pin 42 D3 in the Eagle lib is Pin 42 D2 in the B523 data sheet
Pin 40 D2 in the Eagle lib is Pin 40 D3 in the B523 data sheet

**Comment by AJ-Smoothie** [comment]
Hi! I found this same issue

**Comment by rickkas7** [comment]
This is fixed in version v3

**Comment by rcorvese732** [comment]
Hi, you sent this to the wrong person.
